BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[FoodType] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] NVARCHAR(1000) NOT NULL,
    [remark] NVARCHAR(1000),
    [status] NVARCHAR(1000) NOT NULL CONSTRAINT [FoodType_status_df] DEFAULT 'use',
    CONSTRAINT [FoodType_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
